# Generated by Django 4.2.5 on 2023-11-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_assetconsolidatedvalue_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fixed_income_type',
            field=models.CharField(choices=[('CDB', 'Certificado de Depósito Bancário'), ('LCA', 'Letra de Crédito do Agronegócio'), ('LCI', 'Letra de Crédito Imobiliário'), ('TD', 'Tesouro Direto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='assetconsolidatedvalue',
            name='asset_type',
            field=models.CharField(choices=[('AC', 'Ações'), ('RF', 'Renda Fixa'), ('FII', 'Fundos de Investimento Imobiliário')], max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='asset_type',
            field=models.CharField(choices=[('AC', 'Ações'), ('RF', 'Renda Fixa'), ('FII', 'Fundos de Investimento Imobiliário')], max_length=3),
        ),
    ]
