# Generated by Django 4.2.5 on 2023-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('ticker', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('assert_class', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32, null=True)),
                ('sub_category', models.CharField(max_length=32, null=True)),
                ('ipo_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetprice',
            constraint=models.UniqueConstraint(fields=('ticker', 'date'), name='unique_ticker_date'),
        ),
    ]
