# Generated by Django 4.2.5 on 2023-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='cvm_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='trading_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='mid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='oscillation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assert_class',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cnpj',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
