# Generated by Django 4.2.5 on 2023-10-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asset_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assert_class',
            new_name='asset_class',
        ),
    ]
