# Generated by Django 4.2.5 on 2023-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_assert_class_asset_asset_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprice',
            name='ticker',
            field=models.CharField(max_length=8),
        ),
    ]
