# Generated by Django 4.2.5 on 2023-10-14 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('broker', models.CharField(max_length=32)),
                ('asset_type', models.CharField(choices=[('AC', 'Ações'), ('RF', 'Renda Fixa'), ('FII', 'Fundos de Investimento Imobiliário'), ('TD', 'Tesouro Direto')], max_length=3)),
                ('order_type', models.CharField(choices=[(1, 'buy'), (-1, 'sell')], max_length=4)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('maturity_date', models.DateField(null=True)),
                ('index', models.CharField(choices=[('P', 'Prefixed'), ('S', 'Selic'), ('I', 'IPCA')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
