# Generated by Django 4.2.5 on 2023-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_assetconsolidatedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetconsolidatedvalue',
            name='invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
