# Generated by Django 4.2.5 on 2023-11-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_assetconsolidatedvalue_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetconsolidatedvalue',
            name='asset_type',
            field=models.CharField(choices=[('AC', 'Ações'), ('RF', 'Renda Fixa'), ('FII', 'Fundos de Investimento Imobiliário'), ('TD', 'Tesouro Direto')], default='AC', max_length=3),
            preserve_default=False,
        ),
    ]
