# Generated by Django 4.2.5 on 2023-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asset_company_name_asset_cvm_code_asset_trading_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
